In [37]:
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
#loading the dataset
df=pd.read_csv("../data/raw/gold_prices.csv")
df.head()

         Date        Close         High          Low         Open  Volume
0  2016-01-04  1075.099976  1082.500000  1063.199951  1063.400024     143
1  2016-01-05  1078.400024  1081.500000  1075.300049  1075.599976      82
2  2016-01-06  1091.900024  1093.699951  1081.599976  1081.599976      52
3  2016-01-07  1107.699951  1109.400024  1091.599976  1091.599976     122
4  2016-01-08  1097.800049  1111.099976  1093.000000  1111.099976      98

In [39]:
#Columns presented
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2636 entries, 0 to 2635
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2636 non-null   str
 1   Close   2636 non-null   float64
 2   High    2636 non-null   float64
 3   Low     2636 non-null   float64
 4   Open    2636 non-null   float64
 5   Volume  2636 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 123.7 KB

In [41]:
#number of rows*columns
df.shape

(2636, 6)

In [42]:
df.describe()

             Close         High          Low         Open         Volume
count  2636.000000  2636.000000  2636.000000  2636.000000    2636.000000
mean   1966.106826  1976.864113  1955.058992  1965.969842    5101.193475
std     890.168373   899.440283   881.132336   891.038738   28039.023753
min    1073.900024  1081.500000  1063.199951  1063.400024       0.000000
25%    1308.174957  1311.524994  1304.449951  1308.199951      55.000000
50%    1777.750000  1788.250000  1771.100037  1779.900024     219.500000
75%    2011.825043  2023.675049  2003.024994  2013.975037     683.250000
max    5318.399902  5586.200195  5301.600098  5415.700195  386334.000000

In [43]:
#checking for duplicates values
df.duplicated().sum()

np.int64(0)

In [44]:
#checking for any missing value in each column
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [45]:
#Copying the data to a new dataset
df_cleandata=df.copy()

In [46]:
df_cleandata.duplicated().sum()

np.int64(0)

In [47]:
df_cleandata.dtypes

Date          str
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [49]:
df.head()

         Date        Close         High          Low         Open  Volume
0  2016-01-04  1075.099976  1082.500000  1063.199951  1063.400024     143
1  2016-01-05  1078.400024  1081.500000  1075.300049  1075.599976      82
2  2016-01-06  1091.900024  1093.699951  1081.599976  1081.599976      52
3  2016-01-07  1107.699951  1109.400024  1091.599976  1091.599976     122
4  2016-01-08  1097.800049  1111.099976  1093.000000  1111.099976      98